AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - bin/**/*
    - config/unicorn.rb
    - scripts/**/*
    - spec/**/*
  RunRailsCops: true

Lint/SpaceBeforeFirstArg:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/AbcSize:
  Severity: refactor
  Enabled: false
  Max: 20

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
