default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: coop_development

test:
  <<: *default
  database: coop_test

production:
  <<: *default
  database: coop_production
  username: coop
  password: <%= ENV['COOP_DATABASE_PASSWORD'] %>
